###PHPmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-d
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
          containers:
          - image: phpmyadmin/phpmyadmin:5.0.1
            name: phpmyadmin-c
            env:
            - name: PMA_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-env
                  key: mysql_host
            - name: PMA_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-env
                  key: mysql_user
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            ports:
            - name: phpadmin-p
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30050
  selector:
    app: phpmyadmin
